### PR TITLE
Add json summary output for k6 scenarios

### PR DESCRIPTION
**Pull request by abereziny**
Add json summary output for k6 scenarios preserving also stdout output.

The reasons for this change is to provide ability to tests to have the output json and parse it for test cases purposes.
We also leaving the stdout output for easy human readability.

### CODE REVIEW

**Comment by fyrchik** [comment]
Could you describe the reasons for this change a bit here or in the commit message?

**Comment by fyrchik** [comment]
Also, there is `./k6 run --log-format json` or does it do something different?

**Comment by abereziny** [comment]
> Also, there is `./k6 run --log-format json` or does it do something different?

We don't want time-stamped data-points, just the aggregated summary.

**Comment by abereziny** [comment]
> Could you describe the reasons for this change a bit here or in the commit message?

This is the from the docs:
https://k6.io/docs/results-output/end-of-test/custom-summary/#use-handlesummary

We want:
1. Both outputs (default stdout + json)
2. Json should be end-of-test summary, not log or data-points

**Review by fyrchik — APPROVED** [review]

**Review by dansingjulia — APPROVED** [review]

**Pull request merged**
